In [15]:
import pandas as pd
from pathlib import Path

# Normal Results

In [16]:
folder = Path("../ok")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]
segment_files = [f for f in csvs if f.name.startswith("SEGMENT_")]

print("RESULT files:", len(result_files))
print("SEGMENT files:", len(segment_files))

RESULT files: 22
SEGMENT files: 22

In [17]:

# merge RESULTS
results_df = pd.concat(
    [pd.read_csv(f) for f in result_files],
    ignore_index=True
)

# merge SEGMENTS
segments_df = pd.concat(
    [pd.read_csv(f) for f in segment_files],
    ignore_index=True
)

In [18]:
results_df

,C,gamma,percentile,patient,total_length_hours,TP,FP,FN,sensitivity,precision,...,fpday_k1,sens_k2,f1_k2,fpday_k2,sens_k3,f1_k3,fpday_k3,sens_k4,f1_k4,fpday_k4
0,100.0,0.000436,50,chb01,40.549306,7,5,0,1.000000,0.583333,...,11.837441,1.000000,0.736842,2.959360,0.857143,0.705882,2.367488,0.714286,0.769231,0.591872
1,100.0,0.000436,50,chb02,46.265972,0,9,3,0.000000,0.000000,...,24.899509,0.000000,0.000000,4.668658,0.000000,0.000000,1.037480,0.000000,0.000000,0.000000
2,10.0,0.000436,50,chb03,48.335417,6,29,1,0.857143,0.171429,...,57.100987,0.857143,0.285714,14.399379,0.428571,0.375000,2.979182,0.428571,0.500000,0.993061
3,1.0,0.000873,25,chb04,204.526389,3,687,1,0.750000,0.004348,...,138.935617,0.750000,0.008646,80.615514,0.500000,0.009524,48.580528,0.500000,0.015686,29.218723
4,10.0,0.000873,25,chb06,80.347917,4,29,6,0.400000,0.121212,...,39.428527,0.400000,0.186047,8.662328,0.100000,0.100000,2.688309,0.000000,0.000000,1.194804
5,10.0,0.003922,50,chb07,86.599306,2,18,1,0.666667,0.100000,...,15.796893,0.666667,0.173913,4.988493,0.000000,0.000000,1.662831,0.000000,0.000000,0.277138
6,100.0,0.000436,50,chb08,21.008333,5,22,0,1.000000,0.185185,...,73.113844,1.000000,0.312500,25.132884,1.000000,0.555556,9.139230,1.000000,0.714286,4.569615
7,100.0,0.001307,50,chb09,83.364583,3,17,1,0.750000,0.150000,...,20.152443,0.750000,0.250000,4.894165,0.750000,0.545455,1.151568,0.750000,0.750000,0.287892
8,10.0,0.000436,50,chb10,56.690278,7,18,0,1.000000,0.280000,...,23.284416,1.000000,0.437500,7.620354,0.857143,0.545455,3.810177,0.714286,0.666667,1.270059
9,100.0,0.004386,5,chb11,40.793056,4,23,1,0.800000,0.148148,...,40.006809,0.800000,0.250000,13.531715,0.800000,0.380952,7.060025,0.800000,0.533333,3.530013
10,10.0,0.000436,50,chb12,22.020833,19,32,8,0.703704,0.372549,...,102.448439,0.703704,0.487179,34.876064,0.518519,0.560000,9.808893,0.444444,0.571429,3.269631
11,0.1,0.000436,50,chb13,41.333333,10,353,2,0.833333,0.027548,...,279.870968,0.833333,0.053333,204.967742,0.833333,0.080321,131.806452,0.583333,0.088050,81.290323
12,10.0,0.000436,50,chb14,32.333333,4,3,4,0.500000,0.571429,...,14.103093,0.500000,0.533333,2.226804,0.125000,0.222222,0.000000,0.125000,0.222222,0.000000
13,0.1,0.002618,25,chb16,23.333333,2,12,8,0.200000,0.142857,...,29.828571,0.200000,0.166667,12.342857,0.200000,0.190476,9.257143,0.200000,0.160000,13.371429
14,10.0,0.001307,50,chb17,26.216667,2,1,1,0.666667,0.666667,...,21.055308,0.666667,0.666667,0.915448,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,10.0,0.000436,50,chb18,45.634722,4,4,2,0.666667,0.500000,...,7.888730,0.666667,0.571429,2.103661,0.666667,0.666667,1.051831,0.666667,0.800000,0.000000
16,100.0,0.000436,50,chb19,38.928472,3,22,0,1.000000,0.120000,...,38.840466,1.000000,0.214286,13.563337,1.000000,0.400000,5.548638,1.000000,0.545455,3.082577
17,10.0,0.000873,25,chb20,34.611111,6,11,2,0.750000,0.352941,...,30.510433,0.750000,0.480000,7.627608,0.500000,0.500000,2.773676,0.125000,0.181818,1.386838
18,10.0,0.007853,25,chb21,42.496528,4,6,0,1.000000,0.400000,...,10.730288,1.000000,0.571429,3.388512,0.750000,0.600000,1.694256,0.250000,0.333333,0.564752
19,10.0,0.001307,25,chb22,40.336111,3,2,0,1.000000,0.600000,...,7.140004,1.000000,0.750000,1.190001,1.000000,0.857143,0.595000,1.000000,0.857143,0.595000
20,10.0,0.000436,50,chb23,32.422917,7,13,0,1.000000,0.350000,...,35.530425,1.000000,0.518519,9.622823,0.857143,0.666667,3.701086,0.857143,0.800000,1.480434
21,1.0,0.001307,50,chb24,24.395139,5,30,7,0.416667,0.142857,...,62.963364,0.416667,0.212766,29.514077,0.333333,0.266667,13.773236,0.250000,0.272727,6.886618

In [8]:
results_df.columns

Index(['C', 'gamma', 'percentile', 'patient', 'total_length_hours', 'TP', 'FP',
       'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap',
       'sens_k1', 'f1_k1', 'fpday_k1', 'sens_k2', 'f1_k2', 'fpday_k2',
       'sens_k3', 'f1_k3', 'fpday_k3', 'sens_k4', 'f1_k4', 'fpday_k4'],
      dtype='object')

In [19]:
results_df[['C', 'gamma', 'percentile', 'patient', 'total_length_hours', 'TP', 'FP',
       'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].describe()

,C,gamma,percentile,total_length_hours,TP,FP,FN,sensitivity,precision,f1,FP/day,FP/hour,latency_median,n_detected,mean_fold_roc_auc,mean_fold_ap
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,21.000000,22.000000,22.000000,22.000000
mean,32.827273,0.001428,41.136364,50.570139,5.000000,61.181818,2.181818,0.725493,0.272296,0.357580,22.264172,0.927674,17.178571,4.909091,0.863511,0.398084
std,42.254424,0.001819,13.881455,39.194600,3.829708,157.491235,2.683927,0.278542,0.207381,0.228184,44.420942,1.850873,17.088399,3.878010,0.116407,0.223253
min,0.100000,0.000436,5.000000,21.008333,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.915448,0.038144,-18.500000,0.000000,0.524078,0.014498
25%,10.000000,0.000436,25.000000,32.355729,3.000000,6.750000,0.000000,0.666667,0.126623,0.192726,3.708549,0.154523,13.500000,3.000000,0.827617,0.228727
50%,10.000000,0.000654,50.000000,40.671181,4.000000,17.500000,1.000000,0.750000,0.178307,0.299107,8.144968,0.339374,18.000000,4.000000,0.888389,0.417267
75%,77.500000,0.001307,50.000000,47.818056,6.000000,27.500000,2.750000,1.000000,0.393137,0.529630,14.190369,0.591265,23.000000,6.000000,0.951225,0.561948
max,100.000000,0.007853,50.000000,204.526389,19.000000,687.000000,8.000000,1.000000,0.666667,0.750000,204.967742,8.540323,50.750000,19.000000,0.979570,0.800159

In [7]:
segments_df.describe()

,C,gamma,percentile,n_windows,n_seizure_windows,record_length,threshold,k,roc_auc,ap,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tp,fp,fn
count,578.000000,578.000000,578.000000,578.000000,578.000000,578.000000,578.0,578.0,112.000000,112.000000,112.000000,112.000000,112.000000,107.000000,93.000000,578.000000,578.000000,578.000000
mean,36.082872,0.001764,38.295848,2688.179931,5.840830,6727.949827,0.0,2.0,0.857468,0.390676,0.964270,0.977873,0.296204,0.492758,0.360675,1.740484,27.510381,4.100346
std,43.705129,0.002146,15.835835,2053.179748,18.891158,5132.949369,0.0,0.0,0.161022,0.299063,0.064889,0.063034,0.266048,0.375837,0.244143,5.934809,107.886136,14.481458
min,0.100000,0.000218,5.000000,237.000000,0.000000,600.000000,0.0,2.0,0.327895,0.001851,0.675017,0.674825,0.000000,0.000000,0.008658,0.000000,0.000000,0.000000
25%,1.000000,0.000436,25.000000,1437.000000,0.000000,3600.000000,0.0,2.0,0.799088,0.100953,0.972306,0.990737,0.077516,0.095455,0.134969,0.000000,0.000000,0.000000
50%,10.000000,0.000873,50.000000,1917.000000,0.000000,4800.000000,0.0,2.0,0.931136,0.386574,0.986082,0.997552,0.233333,0.500000,0.347826,0.000000,2.000000,0.000000
75%,100.000000,0.002179,50.000000,1917.000000,0.000000,4800.000000,0.0,2.0,0.978163,0.632900,0.992744,0.999300,0.462821,0.857143,0.566265,0.000000,8.000000,0.000000
max,100.000000,0.019608,100.000000,7691.000000,301.000000,19235.000000,0.0,2.0,0.999426,0.961845,0.999131,1.000000,1.000000,1.000000,0.863636,68.000000,1164.000000,233.000000

In [9]:

# # sort
# results_df = results_df.sort_values(
#     by=["config", "patient"]
# ).reset_index(drop=True)

# segments_df = segments_df.sort_values(
#     by=["config", "patient"]
# ).reset_index(drop=True)


# print(results_df.shape)
# print(segments_df.shape)

In [25]:
results_df.head()

,C,gamma,percentile,patient,total_length_hours,TP,FP,FN,sensitivity,precision,f1,FP/day,FP/hour,latency_median,n_detected,mean_fold_roc_auc,mean_fold_ap
0,10,0.001,10,chb01,40.549306,7,6,0,1.000000,0.538462,0.700000,3.551232,0.147968,24.00,7,0.957437,0.685445
1,10,0.001,10,chb02,46.265972,0,7,3,0.000000,0.000000,0.000000,3.631178,0.151299,NaN,0,0.792279,0.144225
2,10,0.001,10,chb03,48.335417,5,19,2,0.714286,0.208333,0.322581,9.434076,0.393087,36.50,5,0.925757,0.208208
3,10,0.001,10,chb04,204.526389,4,26,0,1.000000,0.133333,0.235294,3.050951,0.127123,63.25,4,0.908047,0.239303
4,10,0.001,10,chb05,50.336806,4,9,1,0.800000,0.307692,0.444444,4.291095,0.178796,24.75,4,0.943870,0.576586

In [26]:
segments_df.head()

,C,gamma,percentile,patient,record,n_windows,n_seizure_windows,record_length,threshold,k,roc_auc,ap,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tp,fp,fn
0,10,0.001,10,chb01,chb01_03,1437,16,3600.0,-1.063608,8,0.991819,0.510324,0.987474,0.992963,0.500000,0.444444,0.470588,8,10,8
1,10,0.001,10,chb01,chb01_04,1437,11,3600.0,-1.004783,8,0.995792,0.743831,0.987474,0.988780,0.818182,0.360000,0.500000,9,16,2
2,10,0.001,10,chb01,chb01_15,1437,16,3600.0,-1.207326,8,0.746481,0.065588,0.965205,0.975369,0.062500,0.027778,0.038462,1,35,15
3,10,0.001,10,chb01,chb01_16,1437,21,3600.0,-1.121530,8,0.989911,0.697757,0.990953,0.995056,0.714286,0.681818,0.697674,15,7,6
4,10,0.001,10,chb01,chb01_18,1437,37,3600.0,1.498560,1,0.995946,0.911562,0.990953,0.999286,0.675676,0.961538,0.793651,25,1,12

In [20]:
# save
results_df.to_csv("RESULTS_MODEL_100_PERCENT.csv", index=False)
segments_df.to_csv("SEGMENTS_MODEL_100_PERCENT.csv", index=False)

In [ ]:
results_df

In [14]:
import time
from sklearn.svm import SVC
print(X_big.shape)          # how big is n, really?
t = time.time()
SVC(C=10, gamma=0.01, kernel='rbf', cache_size=1000).fit(X_big, y_big)
print(time.time() - t, "s")

NameError: name 'X_big' is not defined

# Leaky results

In [42]:
folder = Path("RESULTS_LEAKY")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
leaky_files = [f for f in csvs if f.name.startswith("LEAKY")]

In [44]:
leaky_files

[WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_10.csv'),
 WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_5.csv')]

In [47]:
# merge RESULTS
leaky_df = pd.concat(
    [pd.read_csv(f) for f in leaky_files],
    ignore_index=True
)

In [51]:
leaky_df.head()

,config,C,gamma,percentile,patient,use_all_files,n_train,n_test,test_pos,roc_auc,...,baseline_auprc,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tn,fp,fn,tp
0,A10,0.1,scale,10,chb01,False,8594,955,18,0.996443,...,0.018848,0.978010,0.977588,1.000000,0.461538,0.631579,916,21,0,18
1,B10,0.1,0.01,10,chb01,False,8594,955,18,0.996739,...,0.018848,0.982199,0.982924,0.944444,0.515152,0.666667,921,16,1,17
2,C10,0.1,0.001,10,chb01,False,8594,955,18,0.995612,...,0.018848,0.962304,0.961580,1.000000,0.333333,0.500000,901,36,0,18
3,D10,0.1,0.0001,10,chb01,False,8594,955,18,0.980730,...,0.018848,0.952880,0.954109,0.888889,0.271186,0.415584,894,43,2,16
4,E10,1.0,scale,10,chb01,False,8594,955,18,0.999051,...,0.018848,0.994764,0.995731,0.944444,0.809524,0.871795,933,4,1,17

In [53]:
leaky_df.to_csv("RESULTS_LEAKY.csv", index=False)

# Merge all Results

In [61]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]

print("RESULT files:", len(result_files))

RESULT files: 4

In [13]:
result_files

[WindowsPath('RESULTS/RESULTS_0_10%.csv'),
 WindowsPath('RESULTS/RESULTS_0_5%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_10%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_5%.csv')]

In [21]:
results_0_10 = pd.read_csv(result_files[0]) 
results_0_5 = pd.read_csv(result_files[1]) 
results_10_10 = pd.read_csv(result_files[2]) 
results_10_5 = pd.read_csv(result_files[3])

In [38]:
results_0_10['windows']=0
results_0_5['windows']=0
results_10_10['windows']=10000
results_10_5['windows']=10000

In [39]:
results_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap',
       'windows'],
      dtype='object')

In [40]:
a=results_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

b=results_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

c=results_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

d=results_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

In [43]:
RESULTS = pd.concat([a,b,c,d], ignore_index=False)

In [46]:
RESULTS.to_csv("EVENT_LEVEL_RESULTS.csv", index=False)

# Merge all segments

In [55]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))

# split by filename
segment_files = [f for f in csvs if f.name.startswith("SEGMENTS_")]

print("SEGMENT files:", len(segment_files))

SEGMENT files: 4

In [56]:
segment_files

[WindowsPath('RESULTS/SEGMENTS_0_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_0_5%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_5%.csv')]

In [57]:
segments_0_10 = pd.read_csv(segment_files[0]) 
segments_0_5 = pd.read_csv(segment_files[1]) 
segments_10_10 = pd.read_csv(segment_files[2]) 
segments_10_5 = pd.read_csv(segment_files[3])

In [58]:
segments_0_10['windows']=0
segments_0_5['windows']=0
segments_10_10['windows']=10000
segments_10_5['windows']=10000

In [59]:
segments_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows'],
      dtype='object')

In [60]:
a=segments_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

b=segments_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

c=segments_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

d=segments_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

In [62]:
SEGMENTS = pd.concat([a,b,c,d], ignore_index=False)

In [63]:
SEGMENTS.to_csv("SEGMENT_LEVEL_RESULTS.csv", index=False)

# Other

In [6]:
import pandas as pd

df = pd.read_csv("../RESULTS/BEFORE/0_SEGMENTS.csv")

summary = (
    df.groupby("patient", as_index=False)[["n_windows", "n_seizure_windows"]]
      .sum()
)

summary

   patient  n_windows  n_seizure_windows
0    chb01      58265                180
1    chb02      66515                 70
2    chb03      69489                163
3    chb04     294392                152
4    chb05      72368                224
5    chb06     115647                 64
6    chb07     124646                150
7    chb08      30192                367
8    chb09     119988                111
9    chb10      81559                177
10   chb11      58637                323
11   chb12      31647                401
12   chb13      59421                216
13   chb14      46482                 68
14   chb15      69494                801
15   chb16      33543                 39
16   chb17      37689                118
17   chb18      65606                127
18   chb19      55967                 95
19   chb20      49753                119
20   chb21      61096                 79
21   chb22      57991                 83
22   chb23      46662                173
23   chb24      35063                169

In [7]:
import pandas as pd

df = pd.read_csv("../RESULTS/BEFORE/0_SEGMENTS.csv")

summary = (
    df.groupby("patient")
      .agg(
          Records=("record", "count"),
          Total_Windows=("n_windows", "sum"),
          Seizure_Windows=("n_seizure_windows", "sum"),
      )
      .reset_index()
)

summary["Seizure_Windows (%)"] = (
    100 * summary["Seizure_Windows"] / summary["Total_Windows"]
)

summary

   patient  Records  Total_Windows  Seizure_Windows  Seizure_Windows (%)
0    chb01       42          58265              180             0.308933
1    chb02       36          66515               70             0.105239
2    chb03       38          69489              163             0.234570
3    chb04       42         294392              152             0.051632
4    chb05       39          72368              224             0.309529
5    chb06       18         115647               64             0.055341
6    chb07       19         124646              150             0.120341
7    chb08       20          30192              367             1.215554
8    chb09       19         119988              111             0.092509
9    chb10       25          81559              177             0.217021
10   chb11       35          58637              323             0.550847
11   chb12       21          31647              401             1.267103
12   chb13       33          59421              216             0.363508
13   chb14       26          46482               68             0.146293
14   chb15       40          69494              801             1.152617
15   chb16       19          33543               39             0.116269
16   chb17       21          37689              118             0.313089
17   chb18       36          65606              127             0.193580
18   chb19       30          55967               95             0.169743
19   chb20       29          49753              119             0.239182
20   chb21       33          61096               79             0.129305
21   chb22       31          57991               83             0.143126
22   chb23        9          46662              173             0.370751
23   chb24       22          35063              169             0.481990

In [8]:
results = pd.read_csv("../RESULTS/BEFORE/0_RESULTS.csv")

n_seizures = (
    results.groupby("patient")[["TP", "FN"]]
           .sum()
)

n_seizures["Seizures"] = n_seizures["TP"] + n_seizures["FN"]

summary = summary.merge(
    n_seizures[["Seizures"]],
    on="patient",
    how="left"
)

summary

,patient,Records,Total_Windows,Seizure_Windows,Seizure_Windows (%),Seizures
0,chb01,42,58265,180,0.308933,7
1,chb02,36,66515,70,0.105239,3
2,chb03,38,69489,163,0.234570,7
3,chb04,42,294392,152,0.051632,4
4,chb05,39,72368,224,0.309529,5
5,chb06,18,115647,64,0.055341,10
6,chb07,19,124646,150,0.120341,3
7,chb08,20,30192,367,1.215554,5
8,chb09,19,119988,111,0.092509,4
9,chb10,25,81559,177,0.217021,7
10,chb11,35,58637,323,0.550847,5
11,chb12,21,31647,401,1.267103,27
12,chb13,33,59421,216,0.363508,12
13,chb14,26,46482,68,0.146293,8
14,chb15,40,69494,801,1.152617,20
15,chb16,19,33543,39,0.116269,10
16,chb17,21,37689,118,0.313089,3
17,chb18,36,65606,127,0.193580,6
18,chb19,30,55967,95,0.169743,3
19,chb20,29,49753,119,0.239182,8
20,chb21,33,61096,79,0.129305,4
21,chb22,31,57991,83,0.143126,3
22,chb23,9,46662,173,0.370751,7
23,chb24,22,35063,169,0.481990,12